### ISSUE TITLE
crop image order issue

### ISSUE THREAD

**Issue by shinnobi** [imneonizer/Find-and-Crop-Boxes-in-Images-using-OpenCV-and-Python#1]
i have 2  picture which are same when i apply your method to crop cells from table 
but each picture have different order 
Note that i only crop cells from 2nd row to end
picture 1
![test](https://user-images.githubusercontent.com/21121259/80196258-55e39680-8647-11ea-9408-62bc3b5815af.jpg)

the cropped image is from left to right
this is first picture cropped

![1](https://user-images.githubusercontent.com/21121259/80196488-afe45c00-8647-11ea-8d9f-82b3e9f94a2a.png) 

but when i test with picture 2

![test2png](https://user-images.githubusercontent.com/21121259/80197377-bfb07000-8648-11ea-9faa-6a2c7b921e10.png)

the first picture cropped is

![1](https://user-images.githubusercontent.com/21121259/80196695-efab4380-8647-11ea-80f2-613973f8d13a.png)

(it's from right to left)

**Comment by imneonizer** [comment]
Hi @shinnobi

The codes from the repository is outdated, and is meant to extract only the rows not cells. there is a conditional block which you can play around with to make it work with your own images.

Also it is preforming differently on both of the two input images, because their resolution are different.
I have wrote the code for your use case you can check out [here](https://github.com/imneonizer/Crop-Rows-From-Tables-using-OpenCV-and-Python/tree/master/crop-cells) Hope that helps.

**Comment by shinnobi** [comment]
thanks you very much but i tesed some cases are ok, some case are failed 
this is a picture i tested is failed
![7532](https://user-images.githubusercontent.com/21121259/80353748-f9c77f00-889f-11ea-97be-d38ecb196ae0.jpg)

ps: can you reopen this issues :D sorry  i closed so soon
